import Banner from "@/src/components/Banner";
import Header from "@/src/components/Header";
import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import ProductFeed from "@/src/components/ProductFeed";
import Spinner from "@/src/components/Spinner";

export default function Home() {
  const getProduct = async () => {
    const { data } = await axios.get("https://fakestoreapi.com/products");
    console.log(data);
    return data;
  };
  const { data, isLoading, error } = useQuery(["product"], () => getProduct());

  return (
    <div className="bg-gray-100">
      <Head>
        <title>Online Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="max-w-screen-2xl mx-auto">
        <Banner />

        {isLoading && (
          <div className="flex border-2 h-screen p-40 flex-wrap justify-evenly gap-10 items-center">
            <Spinner />
          </div>
        )}

        {data && <ProductFeed products={data} />}
      </main>
    </div>
  );
}
